### ISSUE TITLE
Sources for functional unit designs

### ISSUE THREAD

**Issue by nblei** [UW-PHARM/BitSAD.jl#33]
I was curious what papers you took the functional unit designs from.  Do you have that list handy?

**Comment by darsnack** [comment]
Sure, here is a list.

- Many of the lowest level designs are from Gaines's original text: http://link.springer.com/10.1007/978-1-4899-5841-9_2
- For linear algebra, I refer to John Hayes's work: http://ieeexplore.ieee.org/document/6927265/
- This is also a good reference as well, particularly for non-linear functions: http://ieeexplore.ieee.org/document/954505/
- IBM's Neurosynaptic System Neuron Function Library Reference Manual. This has designs for IBM's TrueNorth chip that compute quantities using a sigma-delta-like principle. We frequently make use of this concept in our designs. I can't seem to find a link anymore, but if you email me, I can share the PDF.

**Comment by darsnack** [comment]
Of course this project started in 2017, so there may be newer functional units that are worth using as the default designs. I am open to making those changes.
